### ISSUE TITLE
API/ABI changes review

### ISSUE THREAD

**Issue by sjaeckel** [libtom/tomsfastmath#13]
@lvc would you mind adding tomsfastmath to your tool please, including `develop`?

**Comment by lvc** [comment]
Done: https://abi-laboratory.pro/tracker/timeline/tomsfastmath/

![tomsfastmath-1](https://cloud.githubusercontent.com/assets/1517837/24644409/724b0c4c-1924-11e7-9b88-cf72bc6b4b1e.png)

![tomsfastmath-2](https://cloud.githubusercontent.com/assets/1517837/24644353/180958ec-1924-11e7-99f0-e9b9d2c2d7c4.png)

## Environment
* Linux x86_64
* GCC 4.9
* TomsFastMath 0.05 and higher

**Comment by sjaeckel** [comment]
Thanks a lot!
