### ISSUE TITLE
fp_sqr does not handle case when parameter a = 0

### ISSUE THREAD

**Issue by beatsonj** [libtom/tomsfastmath#20]
fp_sqr does not handle case when parameter a = 00....00

When a=00.....00  the result b is not updated.

Adding the following code after y = A->used; seems to resolve this
if (y==0) {
    B->used = 0;
    goto clean;
}

**Comment by sjaeckel** [comment]
IIUC we always hit one of the specialized `sqr_combaXX` implementations or as fall-back the generic `sqr_comba` and each of them correctly sets B->used

You're right, in the case where a=0..0 your proposal would be a shortcut.

Please re-open if I'm wrong, I didn't try it out, but only read through the sources.
