### ISSUE TITLE
fp_iseven() implementation

### ISSUE THREAD

**Issue by muks** [libtom/tomsfastmath#21]
Hi Tom

`fp_iseven()` appears a little incorrect to me, and it should be the following IMO:

```
diff --git a/src/headers/tfm.h b/src/headers/tfm.h
index 0d1dbf1..6f00c08 100644
--- a/src/headers/tfm.h
+++ b/src/headers/tfm.h
@@ -335,7 +335,7 @@ const char *fp_ident(void);
 
 /* zero/even/odd ? */
 #define fp_iszero(a) (((a)->used == 0) ? FP_YES : FP_NO)
-#define fp_iseven(a) (((a)->used >= 0 && (((a)->dp[0] & 1) == 0)) ? FP_YES : FP_NO)
+#define fp_iseven(a) (((a)->used == 0 || (((a)->dp[0] & 1) == 0)) ? FP_YES : FP_NO)
 #define fp_isodd(a)  (((a)->used > 0  && (((a)->dp[0] & 1) == 1)) ? FP_YES : FP_NO)
 
 /* set to a small digit */
```

**Comment by sjaeckel** [comment]
yes, you're right.

**Comment by muks** [comment]
The committed fix is incorrect and differs from the patch provided in this ticket. The operator `||` seems to have been replaced with `&&`. `||` is the correct operator to use.

Please compare the patch committed to the branch vs. the patch quoted in the ticket.

**Comment by sjaeckel** [comment]
thanks a lot for checking this! ...and sorry for the inconvenience :-\
